[package]
name = "mqtt-sql-forwarder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.2"
paho-mqtt = { version = "0.12.3", features=["vendored-ssl"] }
toml = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"
futures-util = "0.3"
async-std = "1"
clap = "4.5"
ctrlc = "3.2"
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
chrono = "0.4.34"
